### ISSUE TITLE
Upgrade to Electron 11

### ISSUE THREAD

**Issue by mlalibs** [SingularityMods/singularity-core#13]
Upgrade Singularity's Electron framework to 11.

**Comment by sbsrnt** [comment]
Just a heads-up as electron is about to [depracate ](https://github.com/electron/electron/issues/21408)`remote` module which is used here https://github.com/SingularityMods/singularity-core/blob/989456f166f9395c657d26c8f53496ae6840ab34/src/services/storage-service.js#L12 and maybe it may break the app.

**Comment by mlalibs** [comment]
Thanks for the heads up!
