### ISSUE TITLE
Unable to verify account

### ISSUE THREAD

**Issue by dunestorm333** [SingularityMods/singularity-core#36]
I've verified my account several times at this point by following the link sent via email, all I see is the following when I login to my account:

> Email: **********@gmail.com (Change)
You still need to**confirm your email address** before you can use all of Singularity's features.

**Comment by mlalibs** [comment]
Hey there! Thanks for the report. I found and fixed the bug on the back end. You should be able to verify with the latest email or click "re-send" and use that link.
