### ISSUE TITLE
Please stop releasing my addons,libs,tools or addons/patches I currently maintain, via your website & addon manager! Thank you

### ISSUE THREAD

**Issue by Baertram** [SingularityMods/singularity-core#57]
Hello there,

I'm Baertram, addon dev for several ESO addons.

I'd like you to stop spreading my addons via your additional website https://singularitymods.com/eso/addons
and via your addon manager software here!

### Please remove ALL of my addons, libraries and other tools/code I'm managing on www.esoui.com from your websites and tools.

**I'm not interested into supporting multiple addon websites and tools!
Minion and www.esoui.com are the only tools I'll support.**

Thank you for your understanding and for following my will about my addons/libs/tools.

Baertram

**Comment by sirinsidiator** [comment]
I agree with Baertram. It's already hard enough to support addon users as is. Having yet another source of install issues is not something I can appreciate. That aside, not asking for permission before hosting my intellectual property is a huge no-go.
So please remove all my addons from your site immediately. You can find the full list [here](https://www.esoui.com/downloads/author-5815.html).

**Comment by torkus** [comment]
There is an interesting parallel drama happening in the Nix world right now: https://news.ycombinator.com/item?id=27553724

If Singularity didn't learn from WoWMatrix and was copying/repackaging addons and hosting them somewhere other than the addon host they were uploaded, I don't have much sympathy - the liability you would open yourself up to! - but @Baertram , @sirinsidiator , for the libraries you have packaged that *do* have licences, they are licenced in a very liberal way that allows repackaging and distribution. I see the Perl Artistic Licence, the Unlicence, CC-BY 4.0 ...

While you guys **absolutely** have the right to *request* that Singularity stop hosting your work, Singularity isn't under any obligation to (except for the libs sans licence, I'd stay way away from those).

If you want to pull this sort of shit:

> not asking for permission before hosting my intellectual property is a huge no-go.
> So please remove all my addons from your site immediately.

pick a different licence.

**Comment by Baertram** [comment]
Thanks for the comment.
I'm not lawyer and doing this in my free time.
I do not want to start a fight about licensing or whatever. I just do not want to have extra work because of users using 20 different sources for the addons and libraries!
The work we had already to clean 1 source was enough. Having several sources, that are even spreading old versions of the code (addons and libs), is just messing up error tracking and user support a lot + forces us to check and invest way more time of our free time, than we want to/or are able to -> The comunity would not benefit from it.

Beside that, every developer/human should be able to simply ASK before spreading stuff. Not only ask the des but also maybe ask the source they take it from. It's simple and my parents at least raised me that way. It's not about licensing, and what lawyers or laws say. It "should be" just "normal" imho.

**Comment by mlalibs** [comment]
Closing as unrelated to the source code project. This is not the place to discuss your concerns over addon mirroring.

**Comment by Baertram** [comment]
There is no "contact" form or similar provided at your website. Maybe add one and we do not need to "abuse" Github.
You cannot asume all ppl are using the provided social media platforms (this definately is not the case), or external tools like Discord (had installed this just to be able to contact you guys). So GitHub was the only way to tell you our "concerns". 

Btw, these were not only concerns about addon mirroring, as sirinsidiator also told you "intellectual property" should not be used without permission!
